package com.mgdapps.cardmagic;

/**
 * Created by HP on 11/30/2016.
 */

public class CardReference {


    int[] cards_oneimage = {R.drawable.cards_zero, R.drawable.cards_one_one, R.drawable.cards_one_two, R.drawable.cards_one_three, R.drawable.cards_one_four, R.drawable.cards_one_five};
    String[] cards_onestring = {"Its really simple but will still amaze the person you are showing it to, however if the person asks you to show the trick to them again DON'T The reason for this is that they may find out what the trick is.",
            "Shuffle the Deck: I know that this is sounds really simple but it is the most crucial part of the trick :-While shuffling you must take a look at the bottom card and memorize it (both number and suit). This will be very important later in the trick.",
            "Pick a Card: Now you fan the cards and ask the person to pick a card, look at it, and put it at the bottom of the deck.",
            "Shuffle the Deck, Again:: This is also very important you must cut the cards up to 4 times (simple but important)",
            "Is This Your Card?"};

    int cards_twoimage[] = {R.drawable.card_two_zero, R.drawable.card_two_one, R.drawable.card_two_two, R.drawable.card_two_three, R.drawable.card_two_four, R.drawable.card_two_five, R.drawable.card_two_six};
    String cards_twostring[] = {"Take two cards from the top deck while keeping them together (so it looks like only one card was drawn. Slip a card directly below the top card in the deck while the deck is behind your back for only a moment.",
            "Ask someone to Draw a card, any card. Tell everyone to look at it. Show it to everyone. Put it under the top card, while the deck is behind your back for a magic moment, where no one can see. If some protest your having the card behind your back, say it is part of the suspense and it's a magic moment",
            "Display the deck and take the top two cards off as one. Show only the bottom card to the audience, as if that pair is one card.",
            "Ask the audience Is this your card? After they confirm Yes!, put the tricky pair back on top of the deck.",
            "Take the trick top card off the top and place it anywhere in the deck. Remember, the picked card is now moved to the top, unknown to the audience. The audience will think that this was their card.",
            "Explain that you will bring it back to the top. You could make a fancy gesture with your hands to really play into the dramatic aspect of the trick.",
            "Turn over the top card while saying Voilà! It will be the chosen card. This trick usually requires only a little bit of practice, but is puzzling to the audience nonetheless."};

    int cards_threeimages[] = {R.drawable.card_three_one, R.drawable.card_three_two, R.drawable.card_three_three, R.drawable.card_three_four, R.drawable.card_three_five, R.drawable.card_three_six};
    String cards_threestring[] = {"Remove the four aces from the deck and place them on top. Don't allow your spectators to see this step. The best way to do this is to place the four aces on top of the deck beforehand. Bring the deck out of your pocket and transition directly into the trick without letting viewers shuffle it.Do this as inconspicuously as possible. Ask, Hey, do you guys want to see a magic trick? and then transition right into it. The more fluid and natural you make it seem, the less the audience will question the trick.,",
            "Split the deck into four even piles by dropping cards from the bottom. Your four aces should naturally end up on the top of the fourth pile. Distribute the piles from left to right so that the fourth pile is to your far right. Don't focus too hard on the fourth pile. Magic involves misdirection, and tricks can easily turn sour if your audience catches on to where the aces are really being kept. Keep talking to distract them a bit.",
            "Pick up the first pile and move the first three cards to the bottom. This gives the illusion that you are shuffling the deck and randomizing cards.",
            "Deal the top three cards onto the other three piles, one card per pile. Start with the pile farthest away from the aces and do the pile with the aces last. Deal only one card per pile. This is especially important when you deal the aces pile, since you will need exactly three random cards above the aces for it to work.",
            "Repeat this with the other three piles. You should end by dealing the aces pile last. By placing the top three cards of the aces pile on the bottom, you have now brought the aces back up to the top of the deck. When you deal them onto the top of the other piles, the top card will always be an ace.",
            "Turn over the top card in each of the four piles and reveal the four aces. If the audience reacts with disbelief, offer to perform the trick again. Once you perfect this trick, switch it up by having the audience members perform the steps. Provide specific instructions for cutting the deck (don't shuffle!), shuffling piles (only the top three cards), and dealing (one card per pile). The outcome will effectively be the same. The difference is that the audience will believe your trick more because they will be duped into thinking they control the outcome."};

    int cards_fourimage[] = {R.drawable.card_four_one, R.drawable.card_four_two, R.drawable.card_four_three, R.drawable.card_four_four, R.drawable.card_four_five};
    String cards_fourstring[] = {"Take out a standard deck of cards and ask an audience member to shuffle it. Encourage the audience member to shuffle it as many times as he or she likes. This trick is based on probability, not misdirection.",
            "Ask the audience member to name any two cards. Request just the name of the card, not the suit. For example, just king and ten will do. Saying king of spades and ten of hearts is more specific and significantly reduces the probability of this trick working. If they mention suits, say something like Hey, I'm new at this, let's just stick with king and ten with a smile. When the audience member says king and ten, she is actually naming four cards of each kind since the suit is not specified. Combined, the two cards create eight total possible cards: king of diamonds, king of clubs, king of hearts, king of spades, ten of diamonds, ten of clubs, ten of hearts, ten of spades. The theory is that of these eight possible cards, at least one of the kings will be next to one of the tens.",
            "Position your hand over the top of the cards and pretend to concentrate hard. Wait about 30 seconds to a minute before continuing with the trick. This helps build the illusion that you actually have something to do with the cards being drawn to each other. This is the only real physical gesture you will make during this trick. Try to have as little to do physically with the trick as possible. This will strengthen the notion that you really performed the illusion.",
            "Tell the audience member to flip over the deck of cards and fan through it. Amazingly, the two cards will (hopefully) appear together somewhere in the deck! Sometimes, there may be a card separating a king and a ten. If this occurs, simply tell the audience that you didn't concentrate hard enough. Perform the trick over and take your chances that the two cards will end up next to each other.",
            "Find the two cards and point them out to the audience. Don't actually touch the cards, otherwise the audience may think you've secretly placed a hidden card next to another."};

    int cards_fiveimages[] = {R.drawable.card_five_one, R.drawable.card_five_two, R.drawable.card_four_three, R.drawable.card_five_four, R.drawable.card_five_five, R.drawable.card_five_six};
    String cards_fivestring[] = {"Hold a deck of cards face-down in one hand. Show the audience that the deck you're holding is just a normal pack of cards. Show them all the cards to help them believe. You can also shuffle the deck or allow audience members to shuffle the deck before you start the trick.",
            "Glance at the bottom card of the deck before holding the cards face-down again. Make sure it's just a quick peek that no one will notice. You will need to remember this card because you will recite it as you show the audience later. Say to yourself in your head, Ace of Diamonds, Ace of Diamonds (or whatever the card is). This will help you remember the card as you proceed with the trick.",
            "Ask the audience to stop you as you skim through the cards. This reinforces the illusion that they are in charge of the trick. Hold the deck face down in one hand. Place the thumb of your other hand underneath the deck. Use the first two fingers of that same hand to pull the cards from the top slightly towards you. If you’ve gone through more than about one fourth of the deck without being stopped, slow down a bit and joke with the audience to see if you can get someone to stop you. This will make drawing the card from the bottom easier.",
            "Slide cards off both the top and bottom of the deck in one motion. Use your index and middle finger to pull the selected cards from the top of the deck into your hand. At the same time, use your thumb underneath the deck to draw the bottom card into that hand. With practice, it will slide unnoticed into the bottom position of the pulled stack of cards. Remember, this bottom card is the one you memorized earlier and will soon reveal as the “guessed” card.",
            "Show the audience the bottom of the pulled deck while holding it away from you. For a better effect, close your eyes or look away as you show the audience the bottom card.",
            "Ask the audience, Is the bottom card the Ace of Diamonds? They should be bewildered that you successfully guessed their card."
    };

    int cards_siximage[] = {R.drawable.card_six_one, R.drawable.card_six_two, R.drawable.card_six_three, R.drawable.card_six_four, R.drawable.card_six_five, R.drawable.card_six_six, R.drawable.card_six_seven, R.drawable.card_six_eight};
    String cards_sixstring[] = {"Fan out a deck of cards while holding them facedown. You don't have to shuffle the deck, although doing so may put the audience members at ease.",
            "Ask a volunteer to pick any card out of the deck. Be patient, because the longer you give the volunteer to pick a card, the more confident they will become that you won't be able to guess it. To help convince the audience, avert your gaze away from the cards as they select. Many audience members assume that guessing tricks are dependent on fancy card counting tricks. While some tricks are, this one is much simpler.",
            "Cut the deck into two stacks after the card is pulled. Place one stack in the right hand and one in the left. Your audience member will most likely choose a card from the middle, so split the cards in a slightly different place from where that card was.",
            "Tell the volunteer to remember the card and place it on top of the pile in your left hand. Speak slowly, confidently, and clearly. Don't rush the volunteer, otherwise the audience may think you've memorized the card beforehand.",
            "Look at the bottom card of the right-hand half of the deck very briefly. While you won't be reciting this card, you will be using it as a reference to find the volunteer's card.",
            "Sandwich the audience member's card between the two halves of the deck. Be sure that you place the right-hand half of the deck on top, as this will be the card that is right next to the volunteer's card.",
            "Spread the cards out on the table faceup. Try to spot the reference card as quickly as possible. Spread the deck out sequentially. The best way to do this is to set the deck down on the left and use your right hand to gently guide them over to the right. The end result should resemble a rainbow. The reference card should be on the left-hand side of the volunteer's card. Whichever card is immediately to the right of the card you memorized should be the audience member's card.Avoid spreading the cards quickly and sloppily. You might accidentally ruin the reference card's position, throwing off the entire trick. You can use your fingers to sort through them, but try not to stop and stare at each card. This might clue in the audience members to what you have actually done."};

    int cards_sevenimage[] = {R.drawable.card_seven_one, R.drawable.card_seven_two, R.drawable.card_seven_three, R.drawable.card_seven_four, R.drawable.card_seven_five, R.drawable.card_seven_six, R.drawable.card_seven_seven};
    String cards_sevenstring[] = {"Look at the top card of the deck and memorize it. For example, ace of spades or seven of hearts. Do this part of the trick out of sight of the audience. It will be more convincing if you pull the cards straight out of your pocket and go directly into the demonstration.",
            "Set the deck face-down, then place a handkerchief over it. Make sure your audience sees the cards facing down before you place the handkerchief over it. For the best effect, make sure the handkerchief is as opaque (non see-through) as possible. Using a handkerchief is a means of distraction. People will assume that the trick is based on visual cues and will dismiss the possibility of you having memorized the card prior.",
            "Turn the deck face-up as you place the handkerchief over it. Be sure you do this while the cards are concealed. Turning the cards too soon will reveal the truth behind the trick. Try to do this as stealthily and quickly as possible. Make placing the handkerchief and flipping the cards one fluid motion so that people only see what is happening on the surface.",
            "Ask an audience member to cut the deck in half while the handkerchief is over it. The volunteer will place the top half of the deck on the other side of the bottom half. Be sure you keep track of which is which and keep the cards concealed. Ask the audience member to only cut the deck in half, not shuffle it. Turning the cards face-up makes the bottom half of the deck become the top. This is important because when you ask the volunteer to cut the deck in half, they will mistakenly believe they are removing the top half when actually it is the bottom.",
            "Bring the real top half of the deck out of the handkerchief while turning the cards face-down. The real top half should contain the top card that you memorized earlier. This is slightly tricky but should be convincing if you make the focus all about the handkerchief. Only remove the top half of the deck. Leave the handkerchief over the bottom half of the deck, which will still be face-up. Wave the hand that will be holding the handkerchief. Try to use fancy gestures to distract the audience from your other hand, which will be turning the cards over.",
            "Ask the audience member to pull the top card from the deck you pulled out. Instruct them to show other members the card without showing you. This is secretly still the top card of the deck, but the audience will think it came from the middle.",
            "Say the name of the card after everyone has seen it. Listen as people gasp in disbelief. Pull the rest of the deck out of the handkerchief while turning them face-down. Do this while the audience is still figuring out how you did the trick. Chances are people will want to inspect the other half of the cards after the trick is done. Give them no reason to question whether or not you flipped them under the handkerchief."};


    int cards_eightimage[] = {R.drawable.card_eight_one, R.drawable.card_eight_two, R.drawable.card_eight_three, R.drawable.card_eight_four, R.drawable.card_eight_five, R.drawable.card_eight_six, R.drawable.card_eight_seven};
    String cards_eightstring[] = {"Position the eights in the deck beforehand. Pull all four eights from the deck. With the deck face down, put one eight on the top of the stack. Place the second eight in the tenth position (that is, count nine cards down, including the top eight). Turn the deck over and count seven cards. Place the final two eights in the eighth and ninth positions. Turn the deck back over. Now you’re ready to go.",
            "Convince the audience that you’re plucking out a random card. Make a big show while fingering through the deck and telling the crowd that you’ll be making a prediction. Fan through the deck once or twice while talking to the audience, then restack the deck. Start fanning cards from one hand the the other, secretly counting to ten. Don’t look at the cards — look at the audience and keep talking. When you get to the tenth card, place your index finger underneath and continue fanning out the deck. Pull out the tenth card (one of the eights) and place it face down on the table. Tell them this is your prediction card.",
            "Flip the deck over. Tell the audience you will be counting through the cards. Pass beyond the two eights in the eighth and ninth positions before telling an audience member Now you can tell me when to stop",
            "Create two piles when the spectator tells you to stop. Place them face down on the table. Place the bottom half of the deck (where the eights are in the eighth and ninth positions) to the right, and the top half of the deck (with the eight on top) to the left.",
            "Flip over the top card of the pile on the left. This will be the eight you placed originally. Look at this card and identify it: Look, it’s the eight of [name the suit]. Then, tell the audience that the eight indicates how many cards you should take from the deck on the right",
            "Count out eight cards from the bottom of the deck on the right. Keep the deck face down. Place these cards in a third pile. Put the third pile on the table (along with the pile that was on the left). Keep the other pile in your hand, face down. Make sure the audience is following. Count out loud One, two, three, … as you create the new pile. Remind them that you now have three piles and that one eight is visible.",
            "Reveal the other eights. Turn over the top card of the pile you just put on the table. It will be an eight. Place it on the table next to the first revealed eight. Then, turn over the pile in your hand and reveal another eight. Place it on the table with the other two. Finally, after building up a bit of anticipation, dramatically flip over your prediction card (which has been on the table face down this whole time). Or, have a spectator make the flip. Expect to see some priceless reactions; this trick fools a lot of people!"};

    int cards_videopage_image[] = {R.drawable.card_nine_zero,R.drawable.card_ten_zero, R.drawable.card_eleven_zero, R.drawable.card_twelve_zero,R.drawable.card_thirteen_zero,
            R.drawable.card_fourteen_zero,R.drawable.card_fifteen_zero,R.drawable.card_seventeen_zero};

    String cards_videopage_string[] = {"Prepare your gimmicked cards as follows. Secure plastic strip to back of card as shown in video.\n" + " Clear flexible plastic can sometimes be found as part of the packaging of new shirts, used to support the collar. Otherwise there are many other sources of packaging where it should be able to be obtained.\n" +
            "The reason for trimming it so that it extends out from each end of the card is so that the thumb base and fingers can easily grip it. This makes the trick a whole lot easier.\n" + "Pressing lightly on each end of the strip will cause it to arch and raise the playing card.\n" + "Tips: Practice this trick in front of a mirror to perfect your angles so that the plastic strip is hidden from the spectator as the card is rising.",

            "Card Trick Magic. A Playing Card Visibly Changes In Front Of You. \n" +
                    "This is a really good magic card trick where a card is seen to change into another card after it has been given a magic rub. This illusion is performed right under your audience's nose which makes it even more convincing. Such is the beauty of close up magic. The How To Magic Instruction Video on this page shows the card trick being demonstrated then gives an explanation of how the magic trick was done. Method : Make sure that the card that you wish to change to is directly under the top card. When you place your hand on top of the cards, gently push the top card up a little. This will expose a little of the second from top card. Now use the fleshy part of your palm ( the part nearest the wrist ) to pull back the second card until it clicks free from the pack. Now push forward and this card should slide over the pack to become the new top card. This move will be hidden from view from your audience who should be viewing the move from above, looking down on the back of your hand. This trick really shows the effectiveness of performing easy but amazing magic tricks.",


            "-This is an easy to perform snap vanish card trick which can be performed with a playing card or a coin. The card appears to mysteriously vanish into nowhere when you bring your hand over it.\n" +
                    "Don't forget though that you should practice this vanishing card trick until you are confident performing it before trying it in front of your friends or an audience. Great easy to do card sleight. Find out the easy method to let you perform this amazing card trick by watching the magic instruction video on this page. This easy card trick shows that with a little practice so that you can perfect the angles and timing, that you can perform very convincing card magic tricks relatively easily. Don't let the simplicity of this sleight fool you, this is a very impressive magic trick secret and usually leaves your audience stunned as a card has seemingly disappeared right in front of their eyes. You can incorporate this sleight into one of your party tricks or combine it with one or two of the other easy magic tricks on this site to perform a cool card trick routine. This is a really cool nice and casual style of close up magic but once you have mastered this method, you may wish to move on to the slightly more advanced, super slick card vanish method. This method although requiring more practice, looks very impressive and is better suited towards a good table magician for hire or wedding magician, should you wish to advertise your services.",


            "-An amazingly convincing levitating card trick in which a spectators freely chosen card is first shuffled into the deck and then made to rise out of the middle of the deck by itself.\n" +
                    "This super card levitation magic trick uses no gimmicks and requires only a pack of playing cards. This is great example of close up magic and is a favorite trick of a lot of good table magicians. Performance : The deck is first shuffled ( It can even be a borrowed deck ) and then fanned out in front of the spectator who is allowed to choose any card, memorize it and then hand it back to be further shuffled into the pack. The pack is then held out directly in front of the spectator where their chosen card is seen to be slowly rising out from the middle of the deck. This looks amazing and will leave your audience baffled as to how they viewed a levitating card right under their nose. Watch the magic video, above to see the performance and secret sleight of hand required to get the best effect from this clever magic showing a levitating card. The pay off is the satisfaction that you get by watching your audience's look of astonishment. Tips : This street magic style rising card trick gets a good response but can be greatly improved by an entertaining performance and chat by the magician. Practicing the timing and smoothness of the card moving up from the deck should pay dividends by enabling you to present a polished performance.",


            "Learn this amazing snap change sleight where a card changes in the blink of an eye, right in front of your spectator. Visually amazing trick\n" +
                    "The card snap change trick is a stunning card sleight which is relatively easy to learn. It requires a little practice to bring it up to speed and to polish your performance but the time invested is well worth it as it looks amazing and can really impress your audience. A card is clearly shown to your spectator. The card suddenly changes into a completely different card right under their nose. This looks stunning and beyond explanation as the card was right in front of them all the time. This stunt goes to prove that an easy trick, performed well can be very effective at impressing your audience. The sleight can also be incorporated into many other illusions. It is an impressive stunt to use as a party trick as it is very visual..",


            "-Card Trick Magic. Make A Playing Card Appear To Melt Through Another Card.\n" +
                    "This is a really good street magic card trick where a card is seen to visibly melt through another playing card. This illusion is performed right under your audience's nose which makes it even more convincing. Such is the beauty of close up magic. The How To Video on this page shows the trick being performed then gives an explanation of how the magic trick was done. There is a little preparation required before performing the card illusion but the time invested is rewarded by the reaction that the trick usually gets. Remember that even though a card trick looks reasonably simple to perform, a little practice will always help you do a more polished performance. You will find many other card and magic tricks within these pages of varying degrees of difficulty. The card melt magic demonstrated on this page makes a good choice for a party trick as it can really create the wow factor.",


            "-A brilliantly simple to do but very impressive card trick where a deck of cards balances in a seemingly impossible position.\n" +
                    "This stunning trick with a deck of cards looks absolutely amazing. A deck of playing cards is carefully placed lengthwise on the fingertips of the magician's outstretched hand. The deck is then seen to be balancing precariously in mid air with only a small portion of the deck actually touching the magicians hand. All logic and your brain keeps telling you that the deck should fall on the table, as it appears to be defying the law of gravity. This is an amazingly impressive card trick to show your friends and needs only a simple set up and a little practice before you will be able to perform this cool balancing act. The video below, shows the magic stunt in action and then shows you the clever secret to enable you to perform this incredible looking balance. It's amazing that such a simple secret can enable such a great looking illusion like this. Highlights : Can be performed almost anywhere there are some easily available items around. Good ice breaker for a bar. The little preparation that is needed to perform this entertaining card magic is time well spent as this trick can look really baffling to your audience. This cool trick goes to show that with a little practice to polish your performance and a few easily found items, that it is possible to perform some simple but very impressive card magic.",


            "This is an impressive find the joker trick, using an easy to do but very clever card sleight known as the glide. The spectator is asked to predict the position of the joker in a pack of cards and amazingly, predicts the correct position every time." +
                    "\n" +
                    "Performance :- Your spectator is asked to predict the position of the joker in the deck of cards that you hold out face down in front of them. They tell you their prediction and that number of cards are dealt from the bottom of the deck and the joker is found to be the card positioned at the spectator's predicted position, every time." +
                    "\n" +
                    "Method :- This card trick depends on a basic card sleight known as the Glide, which involves sliding back the bottom card in the deck slightly, out of view of the spectator." +
                    "\n" +
                    "The magic trick instruction video above, shows the trick being performed and also how to perform the Glide card sleight.",




    };

    int cards_sixteenimage[] = {R.drawable.card_sixteen_one, R.drawable.card_sixteen_two, R.drawable.card_sixteen_three, R.drawable.card_sixteen_four};
    String cards_sixteenstring[] = {"-Don't Be Fooled By This Trick's Simplicity, It Really Works !!!" +
            "\n" +
            "Effect:" +
            "\n" + "You take out a deck of cards and ask the spectator to shuffle it thoroughly. You then ask him to name any two cards (just the name of the card, without the suit). After the spectator names two cards, you put your hand on the deck of cards, and concentrate hard on it. After a minute or so, you ask the spectator to turn over the deck of cards and fan through it. Astonishingly, the cards that he names are right next to each other. You Need:  A deck of cards.",
            "What Skills You Need To Learn: Virtually Nothing! You really don't do anything! If I have to say, the only thing you have to do for this trick is to act like you are really concentrating very hard on the cards when you put your hand on them.",
            "That's all! This trick simply works! All by itself ! This trick works by probability. When the spectator names two cards (remember to tell him not to name the suit), let's say Ace and Ten, he is really naming four cards of each kind since the suit is not specified.",
            "The theory is that out of those eight cards (Ace of Spades Ace of Hearts, Ace of Clubs, Ace of Diamonds, Ten of Spades, Ten of Hearts, Ten of Clubs, Ten of Diamonds), at least one of the Aces in the deck will be next to one of the Tens." +
                    "\n" +
                    "Don't believe this? Try it out! About 10% of the time, there may be a card between the Ace and the Ten. If that happens, simply tell the spectator that you are not concentrating hard enough. When you repeat the trick, it will work. You can never find a trick that's easier than this one!" +
                    "\n" +
                    "Note: This trick can be done to the same spectator a few times, but if you do it too many times, they will eventually figure it out. So, don't overdo this one!"};



    int cards_eighteenimage[] = {R.drawable.card_eighteen_one, R.drawable.card_eighteen_two, R.drawable.card_eighteen_three, R.drawable.card_eighteen_four, R.drawable.card_eighteen_five};
    String cards_eighteenstring[] = {"A spectator selects a card and you find it. At its simplest, the spectator's card can be discovered on the top of the deck. Or you can use any 'reveal' that you wish from simply showing the spectator's selected card on the top of the deck to the 'Rising Card.'",
            "If you like, you can have a spectator mix the cards. Hold the deck so its face is towards spectators and its back is towards you. Pull out the second, third and fourth cards from the back of the deck to display them as in the photo. Allow the top card to remain in place. This is the secret - the spectators don't know about the extra card on top.",
            "Display the cards. The photo shows what spectators see. Remember, as explained in step two, you are secretly holding an extra card behind the others that are fanned at the back of the deck.\n" +
                    "-Ask the spectators to select a card by pointing at individual fanned cards and saying one, two or three, as in the picture.\n" +
                    "-More specifically, the apparent first fanned card (which is actually the second card) is designated 'one'. The apparent second fanned card (which is actually the third card) is designated 'two.' And the apparent third fanned card (which is actually the fourth card) is designated 'three.'\n" +
                    "-Ask the spectator to remember the card based on the number.\n" +
                    "-After the spectator selects a card by naming a number, you gather the cards on top of the deck and allow the unseen and secret first card to stay on top\n",
            "Depending on the number that the spectator selected, you will take that many cards from the top of the deck, individually, and shove them into the middle of the deck. Remember to do this with the deck face down and not in the position where the spectator selected a card.\n" +
                    "-Here's the breakdown according to the number selected by the spectator:\n" +
                    "-Option 1. If the spectator selected 'one', count 'one' and without showing it, take the top card and shove it into the middle of the deck, seemingly losing it.\n" +
                    "-Move to the next step.\n" +
                    "-Option 2. If the spectator selected 'two', count 'one' and take the top card and shove it into the middle of the deck, seemingly losing it. And then count 'two' and without showing it, take the next card and shove it into the middle of the deck. Move to the next step.\n" +
                    "-Option 3. If the spectator selected 'three', count 'one' and take the top card and shove it into the middle of the deck, seemingly losing it. Count 'two' and then take the next card and shove it into the middle of the deck. Count 'three' and without showing it, take the next card and shove it into the middle of the deck.\n" +
                    "-What the spectator doesn't know is that their selected card remains on the top of the deck.",
            "At this point, with the spectator's card on top of the deck, you can utter a magic word and/or wave your hand and show that their card has mysteriously risen to the top of the deck."};


    int cards_nineteenimage[] = {R.drawable.card_nineteen_one, R.drawable.card_nineteen_two, R.drawable.card_nineteen_three, R.drawable.card_nineteen_four};
    String cards_nineteenstring[] = {"In this easy magic card trick, you spin a playing card and it mysteriously floats in mid air underneath your hand. And as if by magic, it slowly rises up - levitates - to your hand so you can catch it. Kids will particularly like this trick.",
            "Using the clear adhesive tape, attach a bit of the thread to the back of the playing card. What you want to do is attach the thread to the center of the playing card, as shown in the picture." +
                    "-Run the other end of the thread over hand and then to a button on your shirt or to a belt buckle. You'll need to anchor the other end of the thread on your body. If you choose to use a button, you can form a loop in the thread and wrap it around the button." +
                    "-If you like, you can also tape the thread to your belt buckle. Of course, you're free to attach the end of thread in any manner that you wish." +
                    "-You'll have to experiment a bit with the length. Basically, you'll want the thread to be fairly taut when you partially extend your arm in front of your body and leave thread so the card will dangle about a foot below your hand.",
            "This image shows the thread running from your body, over hand - between your first finger and second finger - and then to the playing card." +
                    "If you’re right-handed, you’ll want to run the thread over your left hand and launch the card with your right hand. If your left-handed, simply reverse the setup.",
            "To perform the effect, grab the card with your hand. Mimic the motion of launching a Frisbee by folding your hand (bending your wrist), with the card, inwards towards your arm. By quickly straightening your wrist and throwing (spinning) the card, you will cause it to spin on its axis, which is created by the thread at its center.\n" +
                    "-The playing card will float underneath your hand." +
                    "Helpful hints:" +
                    "-Don’t allow spectators to stand too close as they’ll see the thread." +
                    "-It helps to perform this in front of a dark background so the thread tends to blend in with the background." +
                    "-When making the card rise up, try to move your hand slowly. Some practice and experimentation will make this clear so you can make the card rise at a nice pace."};


    int cards_twentyimage[] = {R.drawable.card_twenty_one, R.drawable.card_twenty_two, R.drawable.card_twenty_three};
    String cards_twentystring[] = {"In this easy magic trick, you have a spectator select a card and then lose it in the deck. You place the deck into its box and the spectator's card mysteriously rises out by itself.",
            "Preparation: You’ve cut a hole in the back of the card box. By pressing your first finger against the top card of the deck, you can push it up and make it appear to rise out of the deck and the card box." +
                    "-Find the spectator's card and place it on top of the deck. Place the deck into its card box.",
            "This picture clearly shows how you press against the back card through the box and cause it to rise. This will take some practice. To cover the movement of your first finger, it's a good idea to slowly move the card box in a circular pattern or wave it back and forth. As you move the card box around, the spectator’s card will slowly rise out of its box. When the card is extended as far as you can push it, simply grab it with the other hand and verify that it is the spectator’s chosen card."};


    int cards_twentyoneimage[] = {R.drawable.card_twentyone_one, R.drawable.card_twentyone_two, R.drawable.card_twentyone_three, R.drawable.card_twentyone_four, R.drawable.card_twentyone_five, R.drawable.card_twentyone_six};
    String cards_twentyonestring[] = {"Here's a great and visual easy magic card trick where you cause a playing card to apparently float in air as if it's levitated or suspended above your hand.",
            "Using the picture as a guide, use the blade to cut a tab in the back of one of the playing card. Kids, please get your parents or an adult to help you with this. You'll notice that the tab in the picture is cut at an angle. This affects the angle at which the card \"floats\" over your hand. I happen to think that a non-perpendicular angle makes the effect look better, but you can cut the tab at any angle that you wish.",
            "Fold the tab up. It's this tab that will form the support for the mid-air suspension. This image shows the tab in its folded-out position when the card would apparently “float” over your hand.",
            "Get the second playing card and spread glue on it's back side. Note the areas where you apply glue. You don't want to apply glue to the area of the tab of the first card so that it remains free to move",
            "Apply the gimmicked card with the tab to the card with glue. Be sure to line up the cards so the sides perfectly match-up. Also, it’s best to have the tab in the “up” position so that there’s no way that it adheres to the bottom card. Allow the glue to dry. The picture here shows the gimmicked card in its completed state upside down with the tab extended. Your spectators will not see the card at this angle.",
            "Before you start, press the tab into the back of the card so it's hidden.\n" +
                    "-I'll assume that you will float the card over your left hand. If you want to float the card over your right hand, just reverse the instructions.\n" +
                    "-With the gimmicked card face-up (tab side down), grab the card with your right hand - fingers underneath the card and your thumb on top. Use one of your fingers to hold the tab against the card in its hidden position.\n" +
                    "-You'll notice that if you hold the tab down with a finger as you grasp the card, you can hardly see the tab.\n" +
                    "-Casually show the card on both sides, you don't need to move quickly, Just briefly show the card's back side and then turnover the card so that it's face up.\n" +
                    "-Hold out your left hand and display the gimmicked card face up with your right hand. Maneuver the card over your left hand and briefly rest the card on your left hand fingers.\n" +
                    "-At this point, release the 'tab' under cover of the card and allow it to 'catch' on the fleshy part of the fingers of your left hand to open and fully extend the tab at a 90-degree angle to the card. As you apparently adjust the card with your right hand over the left, allow the tab to fall between the lower parts of your ring and middle finger and grab it there. Continue to raise and \"adjust\" the card with your right hand to cover the movements of your left hand. Raise the card until you can feel your fingers holding the end of the tab.\n" +
                    "-With practice, you'll know when the card feels 'right' and is being supported by the tab without any help from your right hand.\n" +
                    "-At this point, you can briefly release the card and show that it's floating above your left hand.\n" +
                    "-Don't hold the suspension too long. It's just a momentary thing.\n" +
                    "-Grab the card with your fingers underneath the card and your thumb on top, with your finger holding the tab against the card in its hidden position. Casually show both sides of the card.\n" +
                    "-Put the card away.\n" +
                    "-You have caused a card to mysteriously float above your hand."};


    int cards_twentytwoimage[] = {R.drawable.card_twentytwo_one, R.drawable.card_twentytwo_two, R.drawable.card_twentytwo_three, R.drawable.card_twentytwo_four, R.drawable.card_twentytwo_five, R.drawable.card_twentytwo_six, R.drawable.card_twentytwo_seven, R.drawable.card_twentytwo_eight,};
    String cards_twentytwostring[] = {"A Hypercard illusion is a very puzzling piece of origami style trickery, to sculpt a seemingly impossible card object. Baffling to look at yet easy to make for yourself. The Hypercard as you can see, seems to defy logic and can really baffle your onlookers. The impact is even more impressive as you can make one of these incredible paper sculptures in just a few moments, right in front of your audience.",
            "All you will need is a playing card and a pair of scissors. There are three cuts required to be made in the card, the first of which is shown here on the left. Make the cut, a little way into the right side of the card. Cut up as far as the center.",
            "Make a second cut over on the left hand side of the card. Again cut up as far as the center. Take care when using scissors, the cutting parts are best left to an adult to do.",
            "Now, turn the card over and make a final cut in the middle of the edge of the card. As before cut through to the center of the card.",
            "Still holding the card, fold up the bottom right hand portion of the card and align it with the top edge as shown in the photo on the left. Make a little crease along the center fold.",
            "Now fold the bottom left hand portion of the pack away from you and push it up till it meets the top edge of the card (on the side of the card that is facing away from you). Again make a little crease in the middle portion of the card. This portiion to be creased is shown by the lower thumb in the photo on the left.",
            "You can now proceed to untwist your new masterpiece carefully until it resembles something like the photo on the left. You can now place the hypercard on a flat surface.",
            "Make sure that you have properly unfolded the card and that it is lying as flat as possible on the surface where it is to be displayed. Your object of wonderment can now be displayed to the amusement of onlookers who, unless they pick up the card and twist around with it, should be really baffled as to how such an impossible object was made."};

}

